name: syncogen
channels:
  - pytorch
  - anaconda
  - nvidia
  - defaults
dependencies:
  - cuda-nvcc=12.4.99
  - jupyter=1.0.0
  - pip=23.3.1
  - python=3.9
  - pytorch-cuda=12.1
  - pip:
      - torch==2.2.2
      - torchvision==0.17.2
      - torchaudio==2.2.2
      - torch_geometric==2.3.1
      - datasets==2.18.0
      - fsspec==2024.2.0
      - git-lfs==1.6
      - h5py==3.10.0
      - hydra-core==1.3.2
      - ipdb==0.13.13
      - lightning==2.2.1
      - notebook==7.1.1
      - nvitop==1.3.2
      - networkx==3.2.1
      - omegaconf==2.3.0
      - packaging==23.2
      - pandas==2.2.1
      - rich==13.7.1
      - timm==0.9.16
      - wandb==0.13.5
      - rdkit-pypi==2022.9.5
      - rdkit==2024.3.5
      - transformers==4.38.2
      - mypy-extensions==1.0.0
      - black==24.8.0
      - pre-commit==3.8.0
      - typing-extensions==4.11.0
      - einops==0.8.0
